Reorganize script, add license information

diff --git a/cvsgraph.SlackBuild b/cvsgraph.SlackBuild
--- a/cvsgraph.SlackBuild
+++ b/cvsgraph.SlackBuild
@@ -1,37 +1,73 @@
 #!/bin/sh
 #
 # SlackBuild for cvsgraph
-# Written by Georgi D. Sotirov <gdsotirov@dir.bg>
+# Copyright (C) 2007-2010 Georgi D. Sotirov <gdsotirov@dir.bg>
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License
+# as published by the Free Software Foundation; either version 2
+# of the License, or (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+# 
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+#
+# $Id: cvsgraph.SlackBuild,v 1.3 2010/11/14 11:17:21 gsotirov Exp $
 #
 
-. /etc/slack-package.conf
+. ../slack-package.conf
 
 NAME=cvsgraph
 VERSION=1.7.0
-BUILD=1
+BUILD=${BUILD:-1}
 
-cd $TMP
-tar -zxvf $CWD/$NAME-$VERSION.tar.gz
+TMP=${TMP:-/tmp}
+CWD=${CWD:-`pwd`}
+PKG_DIR=${PKG_DIR:-/tmp}
+
+if [ ! -e $TMP ]; then
+  mkdir -p $TMP # location to build the source
+fi
+
 SRC=$TMP/$NAME-$VERSION
-cd $SRC
+if [ -e $SRC -a -d $SRC ]; then
+  echo "Source directory '$SRC' already exists! Plaese, move it or remove it."
+  exit 1
+fi
+
+PKG=$TMP/package-$NAME
+if [ -e $PKG -a -d $PKG ]; then
+  echo "Package creation directory '$PKG' already exists! Please, move it or remove it."
+  exit 2
+fi
+mkdir -p $PKG
+
+# Extract and fix source
+cd $TMP
+tar -xvf $CWD/$NAME-$VERSION.tar.gz
+cd $NAME-$VERSION
 fix_source
 
+# Configure
 CFLAGS=$SLKCFLAGS \
 ./configure --prefix=/usr \
             --sysconfdir=/etc \
             --mandir=/usr/man || exit 1
 
+# Build & install
 make || exit 2
-
-PKG="$TMP/package-$NAME"
-mkdir -p $PKG
-
 make DESTDIR=$PKG install || exit 3
 
 # Complement installation
 install -d -m 755 $PKG/etc
 install -m 644 $SRC/cvsgraph.conf $PKG/etc/cvsgraph.conf.new
 
+# Prepare
 bin_perms $PKG
 (cd $PKG; strip_bin)
 gzip_man $PKG
@@ -48,6 +84,7 @@ install -m 644 $CWD/slack-desc       $PKG/usr/src/slackbuilds/$NAME-$VERSION/sla
 install -m 644 $CWD/slack-required   $PKG/usr/src/slackbuilds/$NAME-$VERSION/slack-required
 install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION/$NAME.SlackBuild
 
+# Assemble package
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
 makepkg -l y -c n $PKG_DIR/$PKGNAME.tgz
@@ -55,7 +92,7 @@ cd $PKG_DIR
 md5sum $PKGNAME.tgz > $PKGNAME.tgz.md5
 cat $PKG/install/slack-desc > $PKGNAME.txt
 
-# Clean up
+# Clean up (optionally)
 if [ "$1" == "--cleanup" ]; then
   rm -r $SRC
   rm -r $PKG
